apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: doki-platform

resources:
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: platform-ui
  app.kubernetes.io/component: platform
  app.kubernetes.io/part-of: doki-stack
  app.kubernetes.io/managed-by: argocd
  doki.io/org-scope: "true"

images:
  - name: platform-ui
    newName: harbor.doki.local/doki-ce/platform-ui
    newTag: latest
