apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vllm
  namespace: doki-ai
  labels:
    app: vllm
    app.kubernetes.io/name: vllm
    app.kubernetes.io/part-of: doki-stack
spec:
  selector:
    matchLabels:
      app: vllm
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
