apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: doki-data
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/part-of: doki-stack
data:
  rabbitmq.conf: |
    default_user = doki
    default_pass = changeme-in-vault
    management.tcp.port = 15672
    vm_memory_high_watermark.relative = 0.7
