apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: doki-data
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/part-of: doki-stack
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: ZG9raQ==
  RABBITMQ_DEFAULT_PASS: Y2hhbmdlbWUtaW4tdmF1bHQ=
