apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: doki-mcp

resources:
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: mcp-scanner
  app.kubernetes.io/component: mcp
  app.kubernetes.io/part-of: doki-stack
  app.kubernetes.io/managed-by: argocd
  doki.io/org-scope: "true"

images:
  - name: mcp-scanner
    newName: harbor.doki.local/doki-ce/mcp-scanner
    newTag: latest
