apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: doki-agents

resources:
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: agent-automation
  app.kubernetes.io/component: agent
  app.kubernetes.io/part-of: doki-stack
  app.kubernetes.io/managed-by: argocd
  doki.io/org-scope: "true"

images:
  - name: agent-automation
    newName: harbor.doki.local/doki-ce/agent-automation
    newTag: latest
