apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: doki-data
helmCharts:
  - name: qdrant
    repo: https://qdrant.github.io/qdrant-helm
    version: "1.16"
    releaseName: qdrant
    namespace: doki-data
    valuesFile: values.yaml
