apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: default-deny-doki-namespaces
spec:
  endpointSelector:
    matchExpressions:
      - key: k8s:io.kubernetes.pod.namespace
        operator: In
        values:
          - doki-data
          - doki-mcp
          - doki-agents
          - doki-platform
          - doki-ee
  ingress: []
  egress: []
