apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - default-deny.yaml
  - allow-doki-mcp.yaml
  - allow-doki-agents.yaml
  - allow-doki-platform.yaml
  - allow-kong-ingress.yaml
  - allow-monitoring.yaml
  - allow-dns.yaml
  - allow-doki-data-ingress.yaml
