apiVersion: v1
kind: Service
metadata:
  name: ee-multi-tenancy
  labels:
    app.kubernetes.io/name: ee-multi-tenancy
    app.kubernetes.io/component: ee
    app.kubernetes.io/part-of: doki-stack
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: ee-multi-tenancy
